### ISSUE TITLE
cross_attention_dim must be specified for CrossAttnDownBlock2D

### ISSUE THREAD

**Issue by mrlihellohorld** [TencentARC/BrushEdit#12]
Traceback (most recent call last):
  File "/home/sobey/lzq/BrushEdit-main/app/src/brushedit_app.py", line 35, in <module>
    from app.src.base_model_template import base_models_template
  File "/home/sobey/lzq/BrushEdit-main/app/src/base_model_template.py", line 55, in <module>
    "pipe": StableDiffusionBrushNetPipeline.from_pretrained(
  File "/home/sobey/anaconda3/envs/brushedit/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/sobey/lzq/BrushEdit-main/src/diffusers/pipelines/pipeline_utils.py", line 817, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/home/sobey/lzq/BrushEdit-main/src/diffusers/pipelines/pipeline_loading_utils.py", line 473, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/home/sobey/anaconda3/envs/brushedit/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/sobey/lzq/BrushEdit-main/src/diffusers/models/modeling_utils.py", line 736, in from_pretrained
    model = cls.from_config(config, **unused_kwargs)
  File "/home/sobey/lzq/BrushEdit-main/src/diffusers/configuration_utils.py", line 259, in from_config
    model = cls(**init_dict)
  File "/home/sobey/lzq/BrushEdit-main/src/diffusers/configuration_utils.py", line 653, in inner_init
    init(self, *args, **init_kwargs)
  File "/home/sobey/lzq/BrushEdit-main/src/diffusers/models/autoencoders/autoencoder_kl.py", line 90, in __init__
    self.encoder = Encoder(
  File "/home/sobey/lzq/BrushEdit-main/src/diffusers/models/autoencoders/vae.py", line 103, in __init__
    down_block = get_down_block(
  File "/home/sobey/lzq/BrushEdit-main/src/diffusers/models/unets/unet_2d_blocks.py", line 128, in get_down_block
    raise ValueError("cross_attention_dim must be specified for CrossAttnDownBlock2D")
ValueError: cross_attention_dim must be specified for CrossAttnDownBlock2D

**Comment by liyaowei-stu** [comment]
This seems to be an issue encountered when loading the model, have you downloaded the checkpoint according to our tutorial, and at the same time, note that the checkpoint folder should contain a config.json file.

e.g., https://huggingface.co/TencentARC/BrushEdit/tree/main/brushnetX

[config.json](https://huggingface.co/TencentARC/BrushEdit/blob/main/brushnetX/config.json)
